name: Run tests

#триггер
on: [ push, workflow_dispatch ]

jobs: #аналог этапов
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps: # шаги конкретной джобы
      - name: Checkout repository # копируем файлы репозитория внутрь CI раннера (агента)
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #кешируем все что хранится в мавен репозитории. Если обновляется pom
      # - будет обновлен и хеш и закешируется заново
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os}}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys:  |
            ${{ runner.os }}-maven-

      - name: Docker info
        run: |
          echo "===== DOCKER VERSION ====="
          docker version

          echo "===== DOCKER INFO ====="
          docker info


      - name: Set up services
        run: bash infra/docker_compose/restart_docker.sh

      - name: Test browser image
        run: |
          docker run -d \
            --name test-chrome \
            --network nbank-network \
            sskorol/selenoid_chromium_vnc:100.0

          sleep 10

          echo "===== CONTAINER ====="
          docker ps -a

          echo "===== LOGS ====="
          docker logs test-chrome || true

          echo "===== INSPECT ====="
          docker inspect test-chrome

          echo "===== BROWSER PORT ====="
          docker run --rm \
            --network nbank-network \
            curlimages/curl:latest \
            curl -v --max-time 5 http://test-chrome:4444/ || true

          docker rm -f test-chrome || true
          

      - name: Run tests
        run: ./mvnw clean test

      - name: Docker diagnostics
        if: always()
        run: |
          echo "===== DOCKER PS ====="
          docker ps -a
          
          echo "===== COMPOSE PS ====="
          docker compose -f infra/docker_compose/docker-compose.yml ps
          
          echo "===== SELENOID LOGS ====="
          docker compose -f infra/docker_compose/docker-compose.yml logs selenoid || true
          
          echo "===== NETWORK ====="
          docker network inspect nbank-network || true